language: java
jdk:
  - oraclejdk8
env:
  matrix:
    - SLF4J_VERSION=1.7.21
    - SLF4J_VERSION=1.6.6

script: "mvn clean install -P build-with-${SLF4J_VERSION} spotbugs:check"
notifications:
  email:
    recipients:
      - skypencil+travis@gmail.com
