language: java
jdk:
  - oraclejdk8
env:
  matrix:
    - SLF4J_VERSION=1.8.0-beta0
    - SLF4J_VERSION=1.7.25
    - SLF4J_VERSION=1.6.6

install: true
script: "mvn clean verify -Dgpg.skip -Dversion.slf4j=${SLF4J_VERSION}"
notifications:
  email:
    recipients:
      - skypencil+travis@gmail.com
