language: java
jdk:
  - oraclejdk7
  - openjdk6
  - openjdk7
env:
  matrix:
    - SLF4J_VERSION=1.7.5
    - SLF4J_VERSION=1.6.6

script: "mvn clean install -P build-with-${SLF4J_VERSION}"
notifications:
  email:
    recipients:
      - skypencil+travis@gmail.com
