package pkg;

public class LdcwToLoadString {
  // declare many constants to increase offset of constant pool.
  // see http://mail-archive.ow2.org/asm/2010-08/msg00013.html

  public static final String field0 = "field0";
  public static final String field1 = "field1";
  public static final String field2 = "field2";
  public static final String field3 = "field3";
  public static final String field4 = "field4";
  public static final String field5 = "field5";
  public static final String field6 = "field6";
  public static final String field7 = "field7";
  public static final String field8 = "field8";
  public static final String field9 = "field9";
  public static final String field10 = "field10";
  public static final String field11 = "field11";
  public static final String field12 = "field12";
  public static final String field13 = "field13";
  public static final String field14 = "field14";
  public static final String field15 = "field15";
  public static final String field16 = "field16";
  public static final String field17 = "field17";
  public static final String field18 = "field18";
  public static final String field19 = "field19";
  public static final String field20 = "field20";
  public static final String field21 = "field21";
  public static final String field22 = "field22";
  public static final String field23 = "field23";
  public static final String field24 = "field24";
  public static final String field25 = "field25";
  public static final String field26 = "field26";
  public static final String field27 = "field27";
  public static final String field28 = "field28";
  public static final String field29 = "field29";
  public static final String field30 = "field30";
  public static final String field31 = "field31";
  public static final String field32 = "field32";
  public static final String field33 = "field33";
  public static final String field34 = "field34";
  public static final String field35 = "field35";
  public static final String field36 = "field36";
  public static final String field37 = "field37";
  public static final String field38 = "field38";
  public static final String field39 = "field39";
  public static final String field40 = "field40";
  public static final String field41 = "field41";
  public static final String field42 = "field42";
  public static final String field43 = "field43";
  public static final String field44 = "field44";
  public static final String field45 = "field45";
  public static final String field46 = "field46";
  public static final String field47 = "field47";
  public static final String field48 = "field48";
  public static final String field49 = "field49";
  public static final String field50 = "field50";
  public static final String field51 = "field51";
  public static final String field52 = "field52";
  public static final String field53 = "field53";
  public static final String field54 = "field54";
  public static final String field55 = "field55";
  public static final String field56 = "field56";
  public static final String field57 = "field57";
  public static final String field58 = "field58";
  public static final String field59 = "field59";
  public static final String field60 = "field60";
  public static final String field61 = "field61";
  public static final String field62 = "field62";
  public static final String field63 = "field63";
  public static final String field64 = "field64";
  public static final String field65 = "field65";
  public static final String field66 = "field66";
  public static final String field67 = "field67";
  public static final String field68 = "field68";
  public static final String field69 = "field69";
  public static final String field70 = "field70";
  public static final String field71 = "field71";
  public static final String field72 = "field72";
  public static final String field73 = "field73";
  public static final String field74 = "field74";
  public static final String field75 = "field75";
  public static final String field76 = "field76";
  public static final String field77 = "field77";
  public static final String field78 = "field78";
  public static final String field79 = "field79";
  public static final String field80 = "field80";
  public static final String field81 = "field81";
  public static final String field82 = "field82";
  public static final String field83 = "field83";
  public static final String field84 = "field84";
  public static final String field85 = "field85";
  public static final String field86 = "field86";
  public static final String field87 = "field87";
  public static final String field88 = "field88";
  public static final String field89 = "field89";
  public static final String field90 = "field90";
  public static final String field91 = "field91";
  public static final String field92 = "field92";
  public static final String field93 = "field93";
  public static final String field94 = "field94";
  public static final String field95 = "field95";
  public static final String field96 = "field96";
  public static final String field97 = "field97";
  public static final String field98 = "field98";
  public static final String field99 = "field99";
  public static final String field100 = "field100";
  public static final String field101 = "field101";
  public static final String field102 = "field102";
  public static final String field103 = "field103";
  public static final String field104 = "field104";
  public static final String field105 = "field105";
  public static final String field106 = "field106";
  public static final String field107 = "field107";
  public static final String field108 = "field108";
  public static final String field109 = "field109";
  public static final String field110 = "field110";
  public static final String field111 = "field111";
  public static final String field112 = "field112";
  public static final String field113 = "field113";
  public static final String field114 = "field114";
  public static final String field115 = "field115";
  public static final String field116 = "field116";
  public static final String field117 = "field117";
  public static final String field118 = "field118";
  public static final String field119 = "field119";
  public static final String field120 = "field120";
  public static final String field121 = "field121";
  public static final String field122 = "field122";
  public static final String field123 = "field123";
  public static final String field124 = "field124";
  public static final String field125 = "field125";
  public static final String field126 = "field126";
  public static final String field127 = "field127";
  public static final String field128 = "field128";
  public static final String field129 = "field129";
  public static final String field130 = "field130";
  public static final String field131 = "field131";
  public static final String field132 = "field132";
  public static final String field133 = "field133";
  public static final String field134 = "field134";
  public static final String field135 = "field135";
  public static final String field136 = "field136";
  public static final String field137 = "field137";
  public static final String field138 = "field138";
  public static final String field139 = "field139";
  public static final String field140 = "field140";
  public static final String field141 = "field141";
  public static final String field142 = "field142";
  public static final String field143 = "field143";
  public static final String field144 = "field144";
  public static final String field145 = "field145";
  public static final String field146 = "field146";
  public static final String field147 = "field147";
  public static final String field148 = "field148";
  public static final String field149 = "field149";
  public static final String field150 = "field150";
  public static final String field151 = "field151";
  public static final String field152 = "field152";
  public static final String field153 = "field153";
  public static final String field154 = "field154";
  public static final String field155 = "field155";
  public static final String field156 = "field156";
  public static final String field157 = "field157";
  public static final String field158 = "field158";
  public static final String field159 = "field159";
  public static final String field160 = "field160";
  public static final String field161 = "field161";
  public static final String field162 = "field162";
  public static final String field163 = "field163";
  public static final String field164 = "field164";
  public static final String field165 = "field165";
  public static final String field166 = "field166";
  public static final String field167 = "field167";
  public static final String field168 = "field168";
  public static final String field169 = "field169";
  public static final String field170 = "field170";
  public static final String field171 = "field171";
  public static final String field172 = "field172";
  public static final String field173 = "field173";
  public static final String field174 = "field174";
  public static final String field175 = "field175";
  public static final String field176 = "field176";
  public static final String field177 = "field177";
  public static final String field178 = "field178";
  public static final String field179 = "field179";
  public static final String field180 = "field180";
  public static final String field181 = "field181";
  public static final String field182 = "field182";
  public static final String field183 = "field183";
  public static final String field184 = "field184";
  public static final String field185 = "field185";
  public static final String field186 = "field186";
  public static final String field187 = "field187";
  public static final String field188 = "field188";
  public static final String field189 = "field189";
  public static final String field190 = "field190";
  public static final String field191 = "field191";
  public static final String field192 = "field192";
  public static final String field193 = "field193";
  public static final String field194 = "field194";
  public static final String field195 = "field195";
  public static final String field196 = "field196";
  public static final String field197 = "field197";
  public static final String field198 = "field198";
  public static final String field199 = "field199";
  public static final String field200 = "field200";
  public static final String field201 = "field201";
  public static final String field202 = "field202";
  public static final String field203 = "field203";
  public static final String field204 = "field204";
  public static final String field205 = "field205";
  public static final String field206 = "field206";
  public static final String field207 = "field207";
  public static final String field208 = "field208";
  public static final String field209 = "field209";
  public static final String field210 = "field210";
  public static final String field211 = "field211";
  public static final String field212 = "field212";
  public static final String field213 = "field213";
  public static final String field214 = "field214";
  public static final String field215 = "field215";
  public static final String field216 = "field216";
  public static final String field217 = "field217";
  public static final String field218 = "field218";
  public static final String field219 = "field219";
  public static final String field220 = "field220";
  public static final String field221 = "field221";
  public static final String field222 = "field222";
  public static final String field223 = "field223";
  public static final String field224 = "field224";
  public static final String field225 = "field225";
  public static final String field226 = "field226";
  public static final String field227 = "field227";
  public static final String field228 = "field228";
  public static final String field229 = "field229";
  public static final String field230 = "field230";
  public static final String field231 = "field231";
  public static final String field232 = "field232";
  public static final String field233 = "field233";
  public static final String field234 = "field234";
  public static final String field235 = "field235";
  public static final String field236 = "field236";
  public static final String field237 = "field237";
  public static final String field238 = "field238";
  public static final String field239 = "field239";
  public static final String field240 = "field240";
  public static final String field241 = "field241";
  public static final String field242 = "field242";
  public static final String field243 = "field243";
  public static final String field244 = "field244";
  public static final String field245 = "field245";
  public static final String field246 = "field246";
  public static final String field247 = "field247";
  public static final String field248 = "field248";
  public static final String field249 = "field249";
  public static final String field250 = "field250";
  public static final String field251 = "field251";
  public static final String field252 = "field252";
  public static final String field253 = "field253";
  public static final String field254 = "field254";
  public static final String field255 = "field255";
  public static final String field256 = "field256";
  public static final String field257 = "field257";
  public static final String field258 = "field258";
  public static final String field259 = "field259";
  public static final String field260 = "field260";
  public static final String field261 = "field261";
  public static final String field262 = "field262";
  public static final String field263 = "field263";
  public static final String field264 = "field264";
  public static final String field265 = "field265";
  public static final String field266 = "field266";
  public static final String field267 = "field267";
  public static final String field268 = "field268";
  public static final String field269 = "field269";
  public static final String field270 = "field270";
  public static final String field271 = "field271";
  public static final String field272 = "field272";
  public static final String field273 = "field273";
  public static final String field274 = "field274";
  public static final String field275 = "field275";
  public static final String field276 = "field276";
  public static final String field277 = "field277";
  public static final String field278 = "field278";
  public static final String field279 = "field279";
  public static final String field280 = "field280";
  public static final String field281 = "field281";
  public static final String field282 = "field282";
  public static final String field283 = "field283";
  public static final String field284 = "field284";
  public static final String field285 = "field285";
  public static final String field286 = "field286";
  public static final String field287 = "field287";
  public static final String field288 = "field288";
  public static final String field289 = "field289";
  public static final String field290 = "field290";
  public static final String field291 = "field291";
  public static final String field292 = "field292";
  public static final String field293 = "field293";
  public static final String field294 = "field294";
  public static final String field295 = "field295";
  public static final String field296 = "field296";
  public static final String field297 = "field297";
  public static final String field298 = "field298";
  public static final String field299 = "field299";

  public void method() {
    System.out.println(field0);
    System.out.println(field1);
    System.out.println(field2);
    System.out.println(field3);
    System.out.println(field4);
    System.out.println(field5);
    System.out.println(field6);
    System.out.println(field7);
    System.out.println(field8);
    System.out.println(field9);
    System.out.println(field10);
    System.out.println(field11);
    System.out.println(field12);
    System.out.println(field13);
    System.out.println(field14);
    System.out.println(field15);
    System.out.println(field16);
    System.out.println(field17);
    System.out.println(field18);
    System.out.println(field19);
    System.out.println(field20);
    System.out.println(field21);
    System.out.println(field22);
    System.out.println(field23);
    System.out.println(field24);
    System.out.println(field25);
    System.out.println(field26);
    System.out.println(field27);
    System.out.println(field28);
    System.out.println(field29);
    System.out.println(field30);
    System.out.println(field31);
    System.out.println(field32);
    System.out.println(field33);
    System.out.println(field34);
    System.out.println(field35);
    System.out.println(field36);
    System.out.println(field37);
    System.out.println(field38);
    System.out.println(field39);
    System.out.println(field40);
    System.out.println(field41);
    System.out.println(field42);
    System.out.println(field43);
    System.out.println(field44);
    System.out.println(field45);
    System.out.println(field46);
    System.out.println(field47);
    System.out.println(field48);
    System.out.println(field49);
    System.out.println(field50);
    System.out.println(field51);
    System.out.println(field52);
    System.out.println(field53);
    System.out.println(field54);
    System.out.println(field55);
    System.out.println(field56);
    System.out.println(field57);
    System.out.println(field58);
    System.out.println(field59);
    System.out.println(field60);
    System.out.println(field61);
    System.out.println(field62);
    System.out.println(field63);
    System.out.println(field64);
    System.out.println(field65);
    System.out.println(field66);
    System.out.println(field67);
    System.out.println(field68);
    System.out.println(field69);
    System.out.println(field70);
    System.out.println(field71);
    System.out.println(field72);
    System.out.println(field73);
    System.out.println(field74);
    System.out.println(field75);
    System.out.println(field76);
    System.out.println(field77);
    System.out.println(field78);
    System.out.println(field79);
    System.out.println(field80);
    System.out.println(field81);
    System.out.println(field82);
    System.out.println(field83);
    System.out.println(field84);
    System.out.println(field85);
    System.out.println(field86);
    System.out.println(field87);
    System.out.println(field88);
    System.out.println(field89);
    System.out.println(field90);
    System.out.println(field91);
    System.out.println(field92);
    System.out.println(field93);
    System.out.println(field94);
    System.out.println(field95);
    System.out.println(field96);
    System.out.println(field97);
    System.out.println(field98);
    System.out.println(field99);
    System.out.println(field100);
    System.out.println(field101);
    System.out.println(field102);
    System.out.println(field103);
    System.out.println(field104);
    System.out.println(field105);
    System.out.println(field106);
    System.out.println(field107);
    System.out.println(field108);
    System.out.println(field109);
    System.out.println(field110);
    System.out.println(field111);
    System.out.println(field112);
    System.out.println(field113);
    System.out.println(field114);
    System.out.println(field115);
    System.out.println(field116);
    System.out.println(field117);
    System.out.println(field118);
    System.out.println(field119);
    System.out.println(field120);
    System.out.println(field121);
    System.out.println(field122);
    System.out.println(field123);
    System.out.println(field124);
    System.out.println(field125);
    System.out.println(field126);
    System.out.println(field127);
    System.out.println(field128);
    System.out.println(field129);
    System.out.println(field130);
    System.out.println(field131);
    System.out.println(field132);
    System.out.println(field133);
    System.out.println(field134);
    System.out.println(field135);
    System.out.println(field136);
    System.out.println(field137);
    System.out.println(field138);
    System.out.println(field139);
    System.out.println(field140);
    System.out.println(field141);
    System.out.println(field142);
    System.out.println(field143);
    System.out.println(field144);
    System.out.println(field145);
    System.out.println(field146);
    System.out.println(field147);
    System.out.println(field148);
    System.out.println(field149);
    System.out.println(field150);
    System.out.println(field151);
    System.out.println(field152);
    System.out.println(field153);
    System.out.println(field154);
    System.out.println(field155);
    System.out.println(field156);
    System.out.println(field157);
    System.out.println(field158);
    System.out.println(field159);
    System.out.println(field160);
    System.out.println(field161);
    System.out.println(field162);
    System.out.println(field163);
    System.out.println(field164);
    System.out.println(field165);
    System.out.println(field166);
    System.out.println(field167);
    System.out.println(field168);
    System.out.println(field169);
    System.out.println(field170);
    System.out.println(field171);
    System.out.println(field172);
    System.out.println(field173);
    System.out.println(field174);
    System.out.println(field175);
    System.out.println(field176);
    System.out.println(field177);
    System.out.println(field178);
    System.out.println(field179);
    System.out.println(field180);
    System.out.println(field181);
    System.out.println(field182);
    System.out.println(field183);
    System.out.println(field184);
    System.out.println(field185);
    System.out.println(field186);
    System.out.println(field187);
    System.out.println(field188);
    System.out.println(field189);
    System.out.println(field190);
    System.out.println(field191);
    System.out.println(field192);
    System.out.println(field193);
    System.out.println(field194);
    System.out.println(field195);
    System.out.println(field196);
    System.out.println(field197);
    System.out.println(field198);
    System.out.println(field199);
    System.out.println(field200);
    System.out.println(field201);
    System.out.println(field202);
    System.out.println(field203);
    System.out.println(field204);
    System.out.println(field205);
    System.out.println(field206);
    System.out.println(field207);
    System.out.println(field208);
    System.out.println(field209);
    System.out.println(field210);
    System.out.println(field211);
    System.out.println(field212);
    System.out.println(field213);
    System.out.println(field214);
    System.out.println(field215);
    System.out.println(field216);
    System.out.println(field217);
    System.out.println(field218);
    System.out.println(field219);
    System.out.println(field220);
    System.out.println(field221);
    System.out.println(field222);
    System.out.println(field223);
    System.out.println(field224);
    System.out.println(field225);
    System.out.println(field226);
    System.out.println(field227);
    System.out.println(field228);
    System.out.println(field229);
    System.out.println(field230);
    System.out.println(field231);
    System.out.println(field232);
    System.out.println(field233);
    System.out.println(field234);
    System.out.println(field235);
    System.out.println(field236);
    System.out.println(field237);
    System.out.println(field238);
    System.out.println(field239);
    System.out.println(field240);
    System.out.println(field241);
    System.out.println(field242);
    System.out.println(field243);
    System.out.println(field244);
    System.out.println(field245);
    System.out.println(field246);
    System.out.println(field247);
    System.out.println(field248);
    System.out.println(field249);
    System.out.println(field250);
    System.out.println(field251);
    System.out.println(field252);
    System.out.println(field253);
    System.out.println(field254);
    System.out.println(field255);
    System.out.println(field256);
    System.out.println(field257);
    System.out.println(field258);
    System.out.println(field259);
    System.out.println(field260);
    System.out.println(field261);
    System.out.println(field262);
    System.out.println(field263);
    System.out.println(field264);
    System.out.println(field265);
    System.out.println(field266);
    System.out.println(field267);
    System.out.println(field268);
    System.out.println(field269);
    System.out.println(field270);
    System.out.println(field271);
    System.out.println(field272);
    System.out.println(field273);
    System.out.println(field274);
    System.out.println(field275);
    System.out.println(field276);
    System.out.println(field277);
    System.out.println(field278);
    System.out.println(field279);
    System.out.println(field280);
    System.out.println(field281);
    System.out.println(field282);
    System.out.println(field283);
    System.out.println(field284);
    System.out.println(field285);
    System.out.println(field286);
    System.out.println(field287);
    System.out.println(field288);
    System.out.println(field289);
    System.out.println(field290);
    System.out.println(field291);
    System.out.println(field292);
    System.out.println(field293);
    System.out.println(field294);
    System.out.println(field295);
    System.out.println(field296);
    System.out.println(field297);
    System.out.println(field298);
    System.out.println(field299);
  }
}
