on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        slf4j:
          - "1.7.32"
          - "2.0.0-alpha4"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          cache: maven
          java-version: 11
          distribution: temurin
      - run: |
         ./mvnw verify -Dversion.slf4j=${{ matrix.slf4j }} -Dgpg.skip -B
